### ISSUE TITLE
关于 CV 还是 resume

### ISSUE THREAD

**Issue by oif** [Qixingchen/CV#1]
我今天也打算写份 MD 的简历放 GitHub 上。
研究了下，发现你是用 CV 所以特意去研究了下 CV 跟 resume 的区别。
发现求职工作的话，应该是用 resume（简历）；学业方面用 CV（履历）会合适点
resume 一般控制在 1 张 A4 纸，而 CV 则一般在 2 张以上

23333

**Comment by Qixingchen** [comment]
2333 现在就不改名字了
